### ISSUE TITLE
Packaging: MANIFEST, META.* files can be generated

### ISSUE THREAD

**Issue by zmughal** [Ensembl/Bio-DB-HTS#104]
These do not necessarily need to be checked in. In particular, as they are now, they interfere with finding the version number if trying to install from the git repository directly:

```shell
$ cpanm --verbose https://github.com/Ensembl/Bio-DB-HTS.git@main
--> Working on https://github.com/Ensembl/Bio-DB-HTS.git@main
[...]
Running Build.PL
Configuring Bio-DB-HTS-2.11 ... WARNING: the following files are missing in your kit:
        DISCLAIMER
Please inform the author.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '3.01'
[...]
Successfully installed Bio-DB-HTS-2.11
```

The META files currently have the version number 2.11.

**Comment by zmughal** [comment]
Also, the DISCLAIMER file refers to Bio-SamTools. It seems to have been copied:

```shell
$ diff -s Bio-SamTools-1.43/DISCLAIMER Bio-DB-HTS-3.01/DISCLAIMER
Files Bio-SamTools-1.43/DISCLAIMER and Bio-DB-HTS-3.01/DISCLAIMER are identical
```

**Comment by sgiorgetti** [comment]
@zmughal - thanks again for your useful heads up and comments.
Please see my reply on issue #101 
We'll be most probably removing/amending these files, as deemed appropriate, while addressing the packaging issue.
I am closing this one for the time being.

Please, feel free to re-open it if you think it worthwhile
