### ISSUE TITLE
Functionality to write bam file

### ISSUE THREAD

**Issue by sb43** [Ensembl/Bio-DB-HTS#14]
Would be handy to have method  available in bio::db::sam that writes bam file.

**Comment by rishidev** [comment]
Yes it would be a useful item to have. At the moment it won't be possible to fit into the development plans, but pull requests are welcome on the matter.

**Comment by andrewyatz** [comment]
Our current focus for `Bio::DB::HTS` is to build the XS bindings required to read the various formats htslib supports. We currently have no need to access the write portions of htslib from Perl. Any pipeline we have that does that kind of work uses the samtools binary. As @rishidev says it would be useful to have generally. We could look at any pull requests on the matter. But we won't be developing these write bindings any time soon.

Marking the issue as closed.

**Comment by sb43** [comment]
Thanks @rishidev and @andrewyatz for your comments and suggesting workaround to use samtools
