### ISSUE TITLE
Looking for some examples of basic FASTA/Q handling with Bio::DB::HTS

### ISSUE THREAD

**Issue by sestaton** [Ensembl/Bio-DB-HTS#2]
First, thanks for the work on this and for making it available on CPAN. I would like to know if there are any plans to add bindings to the FASTA/Q parsing methods in kseq.h of htslib? This may be possible already or by some other method but it is not clear. For reference, @cjfields has already written bindings to kseq.h in the [Bio::Kseq](https://github.com/cjfields/Bio-Kseq) module, which is extremely useful because it is much faster than any pure-Perl parser. I think it would be great to have those basic sequence reading methods in one package along with all the alignment methods.

**Comment by cjfields** [comment]
Just a note: the code in [Bio::Kseq](https://github.com/cjfields/Bio-Kseq) hasn't been released to CPAN and has only basic XS bindings in place.  That being said, it does seem to work fine; if needed I would support it being subsumed into Bio-HTS.

**Comment by rishidev** [comment]
Thanks for raising this. I will have a further look at the repo and if it's OK to bringing it in can do so. One non-technical question that will come up is one of the licencing - just to make it clear what the existing code stands - @cjfields would it be possible to add the Apache2 licence? I think it would simplify matters. Thanks

**Comment by keiranmraine** [comment]
Fasta (indexed with `samtools faidx`) is already handled by `Bio::DB::HTS::Faidx` but the docs are a little mangled.  Here's a basic example which grabs the last 10 bases of each sequence (mouse 37 used here) and takes ~0.05 of a second over NFS (file is 2.6GB):

testFaidx.pl

```
#!/usr/bin/env perl
use strict;
use Bio::DB::HTS::Faidx;

my $ref = shift @ARGV;
my $index = Bio::DB::HTS::Faidx->new($ref);
my @seq_ids = $index->get_all_sequence_ids();
for my $seq_id(@seq_ids) {
  my $full_length = $index->length($seq_id);
  my $location = sprintf '%s:%d-%d', $seq_id, $full_length-9, $full_length;
  my ($seq, $this_length) = $index->get_sequence($location);
  printf "result_length %d, sequence %s, seq_id %s\n", $this_length, $seq, $seq_id;
}
```

Output

```
$ ls -lh mouse_37_genome.fa
-r-xr-x--- 1 cgpref cancer 2.6G Aug 21  2015 mouse_37_genome.fa

$ time perl testFaidx.pl mouse37_genome.fa
result_length 10, sequence ACTGGAATTC, seq_id 1
result_length 10, sequence CCTATGAATT, seq_id 10
result_length 10, sequence GTTAGGGTTA, seq_id 11
result_length 10, sequence GAATGAATTC, seq_id 12
result_length 10, sequence GAAGGAATTC, seq_id 13
result_length 10, sequence TCAGGAATTC, seq_id 14
result_length 10, sequence AATGGAGATC, seq_id 15
result_length 10, sequence AATTGAATTC, seq_id 16
result_length 10, sequence ATGTAGGATC, seq_id 17
result_length 10, sequence TTAGGGTTAG, seq_id 18
result_length 10, sequence GCCTGCTTGC, seq_id 19
result_length 10, sequence GATTACGGGT, seq_id 2
result_length 10, sequence ACTCAACTTC, seq_id 3
result_length 10, sequence GGCATTGGGT, seq_id 4
result_length 10, sequence GGTTAGGGTT, seq_id 5
result_length 10, sequence TCAGCCTTTC, seq_id 6
result_length 10, sequence GTGCTGAAGT, seq_id 7
result_length 10, sequence CTTGTACAAC, seq_id 8
result_length 10, sequence GTGGTAATAG, seq_id 9
result_length 10, sequence ACATTAACAA, seq_id MT
result_length 10, sequence GTTAGGGTTA, seq_id X
result_length 10, sequence NNNNNNNNNN, seq_id Y

real    0m0.051s
user    0m0.020s
sys 0m0.012s
```

**Comment by cjfields** [comment]
@keiranmraine True, but the KSeq bindings also process FASTQ.  It is specifically tuned for use in processing and filtering large sequence data sets (seqtk is the analogous tool for this as samtools is for BAM).

@rishidev I'm open to whatever licensing works, but to be honest I prefer BSD or MIT.

**Comment by keiranmraine** [comment]
@cjfields I was just providing an example specifically for FASTA in case it was of use

**Comment by cjfields** [comment]
@keiranmraine not a problem

**Comment by rishidev** [comment]
@cjfields Would you be OK to make a pull request with kseq added in? That would clear up licencing compatibility concerns.

**Comment by cjfields** [comment]
@rishidev sure, I'll set up a fork and start on this.

**Comment by rishidev** [comment]
@cjfields Thanks

**Comment by andrewyatz** [comment]
Has there been any progress on this? 

I'm worried that we're suggesting to introduce new C dependencies into Bio-HTS. My view on this is Bio-HTS should provide access to routines/functions available from the htslib package. If it's not in htslib then I'm against bringing the code in.

**Comment by rishidev** [comment]
There are functions in kseq.h which is from HTSlib. The Bio::KSeq library as it exists builds for a different kseq.h. The porting plan would be to build for the HTSlib kseq.h, but I don't know if @cjfields has had a chance to look at this yet..

**Comment by andrewyatz** [comment]
Ah okay I had misunderstood this point. Apologies

**Comment by cjfields** [comment]
Nope, hadn't had a chance to be honest, the last four months have been hellish

@andrewyatz @rishidev the header file is present in the HTSLib distribution, but I don't believe the kseq.h functions are 'public' and available directly through the compiled HTS library (libhts I think).  I suspect they are primarily only used under the hood for FASTA.  Bio::KSeq has a compilation step during build to directly compile the C header for the module, but I'm not sure how much that would complicate Bio::HTS compilation.

**Comment by andrewyatz** [comment]
I'm not sure it would complicate it at all @cjfields. If my understanding is correct by doing `#include <kseq.h>` you're going to import the header and all of kseq's code into Kseq.xs. From there you compile the XS as we need to do anyway and out pops the compiled libs.

I've done a quick check by pointing your compilation code away from the klib submodule to my local set of htslib headers and `kseq.h`. I got a working module out of it and 91 very happy test cases.

Looking quickly at the code if kseq was to exist as a separate module under say `Bio::DB::HTS::Kseq` and given POD then it shouldn't be a huge drama.

**Comment by sestaton** [comment]
Thanks for opening the conversation again @andrewyatz. The only thing I'd like to add is that the `Bio::Kseq` module should probably be redesigned slightly so that the iterator returns an object with methods for accessing the id, seq, and qual string. Currently, it returns a hash. This is not a major issue, but it would be inconsistent with the behavior of methods in other Bio::DB::HTS classes.

**Comment by andrewyatz** [comment]
It would be a small change. In @cjfields implementation it seems the iterator object has access to the fields in question. Anyway I think it's relatively simple to bless an object in XS though the exact way escapes me. That way the returned object can be used as a hash or object or you can just use the iterator and ignore all of this other stuff (probably the most efficient way).

**Comment by andrewyatz** [comment]
I took a look at this over the weekend and built something on 55d2055 (feature/kseq). Take a look and see what you think. Usage looks like

``` perl
use feature 'say';
use Bio::DB::HTS::Kseq;
my $kseq = Bio::DB::HTS::Kseq->new('path/to/file');
my $iter = $kseq->iterator();
while(my $seq = $iter->next_seq()) {
  say $seq->seq(); 
}
```

The iterator returns a blessed hash object so all of @cjfields code continues to work with minor modifications to the packages involved. Apart from that I think it works and I've not noticed any major memory leaks.

**Comment by andrewyatz** [comment]
Done a quick test of the memory usage and it seems very static. I think if people are happy with the integration (and licensing) then it can go in without much more fuss.

**Comment by andrewyatz** [comment]
Just done some memory tests on this and usage is static. PR #24 is open for further comment.

**Comment by andrewyatz** [comment]
Seems that @rishidev has just merged this. So I'm marking the thread as closed. @cjfields and @sestaton can you take a look at the APIs and confirm you're okay with them. This work has been licensed under Apache2.0. @cjfields can you say if this is okay?

**Comment by sestaton** [comment]
Everything looks good to me. Thanks for the work on this everyone! It is fine with me to mark this closed, but I would like to know if there will be a new CPAN release with these changes. That would be very helpful.

**Comment by cjfields** [comment]
@andrewyatz @sestaton works for me, just tested it out and everything works fine.  Thanks all, in particular special thanks to @andrewyatz for the effort in moving the code in!

**Comment by andrewyatz** [comment]
Great news and thanks @cjfields but it wouldn't be in if not for your original code. @sestaton I believe @rishidev is winding up for a new release soon so this will make it onto cpan soon.
