### ISSUE TITLE
system exit codes not checked - silent install failures

### ISSUE THREAD

**Issue by keiranmraine** [Ensembl/Bio-DB-HTS#27]
The system calls aren't being checked.  Causes specific issues on minimal installs if `wget` not present:

https://github.com/Ensembl/Bio-HTS/blob/master/INSTALL.pl#L83

**Comment by keiranmraine** [comment]
Additionally, probably sensible to use `curl` in preference  as this is more widely installed on base systems.

**Comment by rishidev** [comment]
I've added a check for the system command fetch. There are also checks for the files being created and unzipped etc that are already present.

I've got wget installed on my system by default and not curl, so it may be one of those things that may depend on your linux flavour.
