### ISSUE TITLE
Build failure under Fedora 23

### ISSUE THREAD

**Issue by biogberg** [Ensembl/Bio-DB-HTS#29]
Build fails under Fedora 23 (4.3.3-303.fc23.x86_64). Perl is 5.22.1 (system), gcc is 5.3.1 (system).
`perl Build.PL`
runs cleanly.

Output from
`perl Build build`
is shown at the end. Compilation dies on: 
`cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]`

It seems to be due to a clash between an option set in Build.PL and options originating in Config_heavy.pm.

Changing -Werror=format-security to -Wno-error=format-security, leads to different compilation errors:
`<command-line>:0:12: error: expected ')' before numeric constant`
occurring twice.

---

Complete compilation output:

`Building Bio-DB-HTS
gcc -I/opt/ghpc/include/htslib -I/usr/lib64/perl5/CORE -DVERSION="2.3" -DXS_VERSION="2.3" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wformat=0 -Wno-unused-result -c -D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=native -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g -o lib/Bio/DB/HTS/Faidx.o lib/Bio/DB/HTS/Faidx.c
cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]
cc1: some warnings being treated as errors
error building lib/Bio/DB/HTS/Faidx.o from 'lib/Bio/DB/HTS/Faidx.c' at /usr/share/perl5/vendor_perl/ExtUtils/CBuilder/Base.pm line 174.`

**Comment by andrewyatz** [comment]
Sounds like it's linked to https://fedoraproject.org/wiki/Format-Security-FAQ#What.27s_the_difference_from_-Werror.3Dformat-security

**Comment by biogberg** [comment]
No, not quite, I’m afraid – it’s not the checking of formats that triggers the error, but the conflict between `–Wformat=0` and the `–Werror=format-security` option that causes compilation to stop.

As noted, when I turn off format-security (`-Wno-error=format-security`), then I get other errors.
`<command-line>:0:12: error: expected ')' before numeric constant`
which I cannot find the origin of.

**Comment by andrewyatz** [comment]
Hmmm interesting. I just do a compilation of it on fedora23. I got it working with the following diff

```
44,47c44,46
<         '-Wno-unused-result',
<         '-Werror=format-security',
<         '-Wformat',
<   ],
---
>         '-Wno-unused-result',
>         '-Werror=format-security',
>   '-Wformat',],
```

So adding `-Werror=format-security` and `-Wformat` in just made it work. Very odd. I got no mention of the `')' before numeric constant` error. Just as an FYI here are my versions
- perl: v5.22.2 from dnf
- gcc: 5.3.1 from dnf

Can you edit your `Build.PL` and see if adding those two flags solves your problem. I have no idea if this will fix things without bad effects on other platforms.

**Comment by biogberg** [comment]
The two cases you diff appear to be identical - apart from whitespace. I deleted the '-Wformat=0' line and got the perl module to build with no problems (a few warnings).

I also added a block to INSTALL.pl that removes the relevant line from Build.PL on the fly in vep-85, and it worked. I'm downloading caches right now.

**Comment by andrewyatz** [comment]
Ah yes sorry my bad. I had two copies of the code on the go and it was getting a bit hairy. Okay that's interesting. @rishidev do we know what the effect is of deleting the `-Wformat=0` line for the compiled code? I guess very little from what @biogberg has said

**Comment by biogberg** [comment]
From the comments in the text it seems it was added to work around some compilation problem with some version of perl. I may just be that it works with current version, but it might break compatibility with older perls.

Maybe inclusion/omission of "-Wformat=0" should be dependent on the perl version?

**Comment by rishidev** [comment]
The '-Wformat=0', was a something left in from the Bio-Samtools days. The accompanying comment is # "turn off warnings originatiNg in Perl's Newx\* calls" so it probably is something that can go if it's causing problems.

As a footnote I did add in the '-Wno-error' and  '-Wno-unused-result' as Fedora 21 resulted in a load of trivial warnings that got treated as errors and prevent compilation on that platform.

**Comment by rishidev** [comment]
The -Wformat=0 has no been removed from the default build options.
