### ISSUE TITLE
Ancillary items from Bio-SamTools

### ISSUE THREAD

**Issue by ghost** [Ensembl/Bio-DB-HTS#32]
@keiranmraine created a ticket on the perviously copied repo, so I'm reopening it as it's been lost. 

bam2bedgraph is missing, however Bio-DB-HTS also doesn't include the utility perl scripts that use it. 
I have written an htslib dependant version of bam2bedgraph **(NB the input style is slightly different)**. 
Should you choose to include it you can find it here:

https://github.com/ICGC-TCGA-PanCancer/PCAP-core/blob/dev/c/bam2bedgraph.c

**Comment by andrewyatz** [comment]
Thanks @drjsanger that's pretty cool :).

My biggest question is if this library is the best place for this kind of tool. The utility is there (we also create BigWigs of coverage from BAMs) just do we think this is the right place for it? There's also http://bedtools.readthedocs.io/en/latest/content/tools/genomecov.html which at a cursory glance looks to have similar goals to this code.

Can you comment on if this is better/worse/no different to the bedtools version?

**Comment by keiranmraine** [comment]
It would be nice if Bio::DB::HTS supported the complete Bio::DB::Sam as an HTS replacement.  This code was part of the tools for use under GBrowse.  If all of the missing bits were also ported then anyone with a need to continue using GBrowse but with CRAM would have a drop in replacement.

FYI, genomecov doesn't support any form of read filtering so you have to pipe data through additional tools to filter to a representative dataset (you really don't want duplicates, supplementary data in your coverage plots).

@drjsanger has actually improved upon the old version as it exposes the filtering options. He's also written a more efficient tool for cat'ing per-chromosome BigWig files, [`bwcat`](https://github.com/ICGC-TCGA-PanCancer/PCAP-core/blob/dev/c/bwcat.c), so parallel generation of the data can be achieved (the version in [kentUtils](https://github.com/ENCODE-DCC/kentUtils) was in-efficient).  We use this approach in [`bamToBw.pl`](https://github.com/ICGC-TCGA-PanCancer/PCAP-core/blob/2e3889e4deb33c1877c53fc89e3d7d2ef0e21e2d/bin/bamToBw.pl) (also accepts cram).

**Comment by rishidev** [comment]
Bio::DB::HTS was intended to provide library hooks into the HTSlib API. It can never replicate the old Bio::DB::Sam as there were C functions that had been moved to samtools in the split that wasn't in HTSlib, and would have meant bringing in samtools 1.0+ code. There has already been lost functionality. 

I know this is useful code but providing add-ons doesn't quite fit with the project philosophy of providing a CPAN distributable Perl library.  Perhaps the place to bring this into is to provide it as an update to the original GMOD/GBrowse-Adaptors?

**Comment by keiranmraine** [comment]
I just wanted to clarify if this was the intent.  If your project can't support this that's fine.

**Comment by rishidev** [comment]
Thanks.
