### ISSUE TITLE
Error while installing VEP

### ISSUE THREAD

**Issue by raonyguimaraes** [Ensembl/Bio-DB-HTS#33]
Hi I just received this error while installing VEP from ensembl-tools. What can be wrong?

```
** GET https://codeload.github.com/Ensembl/Bio-DB-HTS/zip/master ==> 200 OK (2s)
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-HTS-master - moving files to ./biodbhts
ERROR: Could not move directory
No such file or directory at INSTALL.pl line 563.
```

**Comment by rishidev** [comment]
Hi - the Bio::DB::HTS repo has undergone a name change to Bio::HTS, but there was an update made to the VEP installer script to reflect this. If you are using the latest release/85 branch of ensembl-tools it should pick up this change. Let me know if this works
https://github.com/Ensembl/ensembl-tools/commit/066fa73a08529e917ac5f0979e2bd7df016a2f31

**Comment by raonyguimaraes** [comment]
Yes upgrading to 85 did solve the problem, thanks. I guess you should fix for older versions such as version 84 just not to render them unusable as they are now.
Regards.
