### ISSUE TITLE
Coverage from Cram input

### ISSUE THREAD

**Issue by ghost** [Ensembl/Bio-DB-HTS#37]
Hi,
I'm trying to retrieve average coverage over chr20 from a cram file.

I used the following perl script: 
```perl 
use strict;
use warnings;
use Bio::DB::HTS;
my $hts= Bio::DB::HTS->new(-bam  => "aln.cram",
					-fasta =>"ref.fa",
					);
my ($coverage) = $sam->get_features_by_location(-type=>'coverage',-seq_id=>"chr20");
my @data = $coverage->coverage;
my $total;
for (@data) { $total += $_ }
my $average_coverage = $total/@data;

```
With it and my cram file, I got an average coverage of 0.15, which seems particularly low.
 I wanted to check if I got the same average coverage with a bam file. To do so, I converted my cram file to bam using the following command: 
```
samtools view -b -h aln.cram -o aln.bam -T ref.fa
```
I ran the same perl code for this bam and get an average coverage of 5.16 ...

Why is there a difference and is there any way to get the same average coverage result? 

Thank you in advance for your answer.

**Comment by rishidev** [comment]
Thanks for raising this. Just to confirm that I have been able to duplicate the issue, and am investigating further. Will update in due course.

**Comment by rishidev** [comment]
Hi

It looks like there is an issue with determining the end point for the coverage. The fix still needs to go in but how do you fare if you specify the end location?

  my ($coverage) = $hts->get_features_by_location(-type=>'coverage',-seq_id=>"XV", -start=>"1", -end=>"1091291");

**Comment by rishidev** [comment]
@Schmurf87  The fix is on the bugfix/avg_coverage_2016 branch if you'd like to test it please 
https://github.com/Ensembl/Bio-DB-HTS/tree/bugfix/avg_coverage_2016

**Comment by ghost** [comment]
It works perfectly !!
Thank you for your work.

**Comment by rishidev** [comment]
Glad it worked, the fix has now merged into master
