### ISSUE TITLE
Switch to using hisremote

### ISSUE THREAD

**Issue by andrewyatz** [Ensembl/Bio-DB-HTS#46]
Currently Bio::HTS::Lib has its own routine for deciding if a given location is a remote or locally hosted file. htslib now has `hisremote()`, which does the same thing. We should switch to using this routine rather than using our own version

**Comment by rishidev** [comment]
Thanks @andrewyatz , fixed with https://github.com/Ensembl/Bio-DB-HTS/pull/47
