### ISSUE TITLE
BCF indexing

### ISSUE THREAD

**Issue by rishidev** [Ensembl/Bio-DB-HTS#55]
It would be good to be able to have the ability to jump straight into an indexed BCF file, perhaps using the  bcf_sr_seek function in HTSlib.

**Comment by avullo** [comment]
This is finally in place. The interface is pretty similar to one provided for tabix indexed files, just invoke the query method (passing a region) on an either VCF tabix indexed or BCF CSI indexed file to obtain an iterator. Individual results can then be accessed as VCF rows by repeatedly invoking the iterator next method until nothing is returned. See e.g.

https://github.com/Ensembl/Bio-DB-HTS/blob/master/t/05vcf.t#L378

**Comment by andrewyatz** [comment]
Pretty awesome work :+1:

**Comment by avullo** [comment]
Thanks! This can open interesting opportunities for both variation and web.
