### ISSUE TITLE
Does not support csi index

### ISSUE THREAD

**Issue by keiranmraine** [Ensembl/Bio-DB-HTS#57]
The perl code doesn't handle the more efficient `csi` index for bam files:

https://github.com/Ensembl/Bio-DB-HTS/blob/master/lib/Bio/DB/HTS.pm#L2146

**Comment by andrewyatz** [comment]
Don't think we're up to the latest htslib version yet ... do we just need to add in `{path}.csi` into this bit of code?

**Comment by keiranmraine** [comment]
csi has been in samtools/htslib for over a year, it's not new.

I think this block is the most of it:

https://github.com/Ensembl/Bio-DB-HTS/blob/064b8699d3ffb2e54c6ad14bbbcf385447112d36/lib/Bio/DB/HTS.pm#L2145-L2160

But is also looks like the `reindex` function has a bug if you had cram:

https://github.com/Ensembl/Bio-DB-HTS/blob/064b8699d3ffb2e54c6ad14bbbcf385447112d36/lib/Bio/DB/HTS.pm#L2188

**Comment by rishidev** [comment]
There is also get_index_fmt_from_extension() which assumes a BAM file will have bai index to have a look at

https://github.com/Ensembl/Bio-DB-HTS/blob/064b8699d3ffb2e54c6ad14bbbcf385447112d36/lib/Bio/DB/HTS.xs#L327

It would be good if csi could be made the default if the index needs to be generated. As well as being more efficient it handles long read use cases. bai support may potentially be dropped in a BAM v2.

**Comment by keiranmraine** [comment]
I don't think you can just drop `bai`.  My understanding is htslib/samtools will continue to support reading with bai for a considerable time.  I doubt people with large stores of data will rapidly switch to csi for legacy data.

Makes sense to set it as the default when generating though.

**Comment by andrewyatz** [comment]
Not sure how you can fix `get_index_fmt_from_extension()` @rishidev. The routine assumes a single return for a format. Now there's two possible indexes for a given format.

**Comment by keiranmraine** [comment]
Is that function actually used (or documented as usable)? I can't see any reference to it elsewhere in the code base.

**Comment by andrewyatz** [comment]
If we can delete it then that would be so much easier to deal with

**Comment by keiranmraine** [comment]
See #58

**Comment by avullo** [comment]
At this stage, could csi be made the default if the module is provide support for an older htslib?
One way I see this possible is for the HTS to detect somehow the library version and pass the required min_shift argument to XS.
