### ISSUE TITLE
Archives install script tied to master

### ISSUE THREAD

**Issue by avullo** [Ensembl/Bio-DB-HTS#59]
The install script for previous releases downloads and builds the master branch code.
An excerpt from running it for 2.7, showing how it is bound to the current release number as set in master (2.9):

*** Building Bio::DB::HTS ***
***CMD*** : env HTSLIB_DIR=/tmp/lCFQHly_Rz/htslib perl Build.PL
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.9'
Building Bio-DB-HTS
cc -I/tmp/lCFQHly_Rz/htslib/htslib -I/home/avullo/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE -DXS_VERSION="2.9" -DVERSION="2.9" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wno-unused-result -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/HTS.bs')
 ...

This is about introducing a version variable in the install script, and keeping it in sync at release time with the version number as set in the various modules.

**Comment by keiranmraine** [comment]
Long standing: https://github.com/Ensembl/Bio-DB-HTS/issues/15#issuecomment-220273793

**Comment by avullo** [comment]
Thanks @keiranmraine, did not sift through past issues and hadn't realised this was already known. Anyway, it's good now it's officially captured.

**Comment by avullo** [comment]
Ok, the INSTALL script from next release on (>= 2.10) will download/build/install the version associated to the archive or the latest release if cloned from master.
