### ISSUE TITLE
Memory leak in Faidx.pm/xs

### ISSUE THREAD

**Issue by keiranmraine** [Ensembl/Bio-DB-HTS#6]
Hi,

It looks like there is a mem leak in the Faidx.pm/xs module:

```
$ /usr/bin/time perl snpPanelGcCorrections.pl genome.fa SnpPositions.tsv
    Chr Position    ...
AUTO_1  1   3023783 ...
0.19user 0.02system 0:00.22elapsed 97%CPU (0avgtext+0avgdata 129104maxresident)k
0inputs+0outputs (0major+10915minor)pagefaults 0swaps

$ /usr/bin/time perl snpPanelGcCorrections.pl genome.fa SnpPositions.tsv
    Chr Position    ...
AUTO_1  1   3023783 ...
AUTO_2  1   3036178 ...
0.36user 0.03system 0:00.40elapsed 97%CPU (0avgtext+0avgdata 237648maxresident)k
0inputs+0outputs (0major+18918minor)pagefaults 0swaps

$ /usr/bin/time perl snpPanelGcCorrections.pl genome.fa SnpPositions.tsv
    Chr Position    ...
AUTO_1  1   3023783 ...
AUTO_2  1   3036178 ...
AUTO_3  1   3050521 ...
0.52user 0.06system 0:00.60elapsed 95%CPU (0avgtext+0avgdata 308112maxresident)k
0inputs+0outputs (0major+25291minor)pagefaults 0swaps
```

Each line is the result of 16 requests against faidx around a position increasing up to 10mb

**Comment by keiranmraine** [comment]
Simple script to show this issue:

```
#!/usr/bin/perl

use strict;
use Bio::DB::HTS::Faidx;
use Devel::Size qw(size total_size);

my ($ref, $iter) = @ARGV;

my $index = Bio::DB::HTS::Faidx->new($ref);
printf "Faidx object before use is %.2fk\n\n", total_size($index)/1024;

for(0..($iter-1)) {
  my ($seq, $length) = $index->get_sequence("1:1-1000000");
  printf "seq of length %d uses %.2fk\n", $length, size($seq)/1024;
  printf "Faidx object using %.2fk\n\n", total_size($index)/1024;
}
```

**Comment by keiranmraine** [comment]
Example output for 1 and 10 iterations:

```
$ /usr/bin/time -v perl htsFaidx.pl test.fa 1
Faidx object before use is 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
    Command being timed: "perl htsFaidx.pl test.fa 1"
    ...
    Maximum resident set size (kbytes): 19920
        ...
    Exit status: 0

$ /usr/bin/time -v perl htsFaidx.pl test.fa 10
Faidx object before use is 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
seq of length 1000000 uses 976.61k
Faidx object using 0.07k
    Command being timed: "perl htsFaidx.pl test.fa 10"
    ...
    Maximum resident set size (kbytes): 58960
    ...
    Exit status: 0
```

**Comment by keiranmraine** [comment]
Test::Valgrind gives the following output:

```
$ (perl -MTest::Valgrind htsFaidx.pl 1 > output.out) >& output.err
$ cat output.out
1..15
ok 1 - InvalidFree
ok 2 - MismatchedFree
not ok 3 - InvalidRead
ok 4 - InvalidWrite
ok 5 - InvalidJump
ok 6 - Overlap
ok 7 - InvalidMemPool
ok 8 - UninitCondition
ok 9 - UninitValue
ok 10 - SyscallParam
ok 11 - ClientCheck
not ok 12 - Leak_DefinitelyLost
not ok 13 - Leak_IndirectlyLost
ok 14 - Leak_PossiblyLost
not ok 15 - Leak_StillReachable
```

**Comment by ghost** [comment]
Just to add to this. I suspect it is because the XS variable seq is never freed. 

The following is an extract form the htslib code. 

>   /*!
>       @abstract    Fetch the sequence in a region.
>       @param  fai  Pointer to the faidx_t struct
>       @param  reg  Region in the format "chr2:20,000-30,000"
>       @param  len  Length of the region; -2 if seq not present, -1 general error
>       @return      Pointer to the sequence; null on failure
>       @discussion The returned sequence is allocated by malloc family
>       and should be destroyed by end users by calling free() on it.
>      */
>     char *fai_fetch(const faidx_t *fai, const char *reg, int *len);

**Comment by andrewyatz** [comment]
@drjsanger it looks like seq is freed after it gets copied into a new SV https://github.com/Ensembl/Bio-HTS/blob/master/lib/Bio/DB/HTS.xs#L386.

**Comment by keiranmraine** [comment]
@andrewyatz that's not the same code, that is 'Bio::DB::HTS::Fai' (directly ported from Bio::DB::Sam) not 'Bio::DB::HTS::Faidx', Faidx is more useful as it includes:

```
$faidx->get_all_sequence_ids();
$faidx->length($seq_id);
```

These are only available if you have a Htsfile object otherwise (which you won't when just using fasta).

Relevant bits are:

https://github.com/Ensembl/Bio-HTS/blob/master/lib/Bio/DB/HTS/Faidx.xs#L133-L140
and 
https://github.com/Ensembl/Bio-HTS/blob/master/lib/Bio/DB/HTS/Faidx.xs#L60-L76

If you just add `free((void*)seq)` to this you get errors as you clear the value you're passing back (at least I think that's what happens)

**Comment by andrewyatz** [comment]
Apologies quite right I was in the wrong place. Okay yes that will be an issue if it doesn't free the char

**Comment by andrewyatz** [comment]
Okay plot thickening. Not sure if @rishidev has seen this. We do free the char at https://github.com/Ensembl/Bio-HTS/blob/master/lib/Bio/DB/HTS/Faidx.xs#L70-L75. The call you flagged up uses this other subroutine, which does issue a free to the seq afterwards.

From some quick observations I've made from looking at the binary on my machine
1. Memory consumption seems to explode when the `sv_catpv` line is on
2. Once I comment out `sv_catpv` memory still increases but at a more consistent and smaller rate
3. Commenting out `free()` really makes the memory consumption go through the roof
4. Creating a new Faidx object doesn't help to keep the memory consumption down
5. Very oddly if I comment out everything apart from `*seq = newSVpvn("",0);` I can still cause an increase in resident memory size.

I had a version of the code that only carried out htslib actions and the memory usage was constant. The moment I brought in the SV work in memory started to grow. Somehow the SV is being mis-handled. However what makes it really odd is that doing a `Devel::Peek` on the results shows refcount being 1. Here's an example:

```
#SEQ
SV = PV(0x7fa84a8043b0) at 0x7fa84a853fc8
  REFCNT = 1
  FLAGS = (PADMY,POK,pPOK)
  PV = 0x7fa84a407980 ""\0
  CUR = 0
  LEN = 16
```

```
#LEN
SV = IV(0x7fa84b803c48) at 0x7fa84b803c58
  REFCNT = 1
  FLAGS = (PADMY,IOK,pIOK)
  IV = 1000
```

```
# FAIDX object
SV = IV(0x7fa84a82dc90) at 0x7fa84a82dca0
  REFCNT = 1
  FLAGS = (PADMY,ROK)
  RV = 0x7fa84a8062b0
  SV = PVMG(0x7fa84a84d550) at 0x7fa84a8062b0
    REFCNT = 1
    FLAGS = (OBJECT,IOK,READONLY,pIOK)
    IV = 140360778001984
    NV = 0
    PV = 0
    STASH = 0x7fa84a834480  "Bio::DB::HTS::Faidx"
```

There's some real horrible magic going on here ...

**Comment by keiranmraine** [comment]
I've tried a few things but my C/XS foo isn't getting me far.  The only thing I've spotted is that there is a warning about creating PVs inline like here, but this doesn't seem to be the cause (but thought I'd mention it as it's in quite a few places):

https://github.com/Ensembl/Bio-HTS/blob/98177d8edb445a747442ea5d0099cf14453fc1bf/lib/Bio/DB/HTS/Faidx.xs#L70

From perlguts:

> Also remember that C doesn't allow you to safely say foo(SvPV(s, len), len);. It might work with your compiler, but it won't work for everyone. Break this sort of statement up into separate assignments...

Updated example code which drops the perl-heap for each iteration:

```
#!/usr/bin/perl
use strict;
use Bio::DB::HTS::Faidx;
use Devel::SizeMe qw(total_size perl_size heap_size);

my ($ref, $iter) = @ARGV;
my $index = Bio::DB::HTS::Faidx->new($ref);
my @summary = (sprintf "Faidx object before use is %.2fk\n", total_size($index)/1024);
for(0..($iter-1)) {
  my ($seq, $length) = $index->get_sequence("1:1-1000000");
  push @summary, sprintf "%s seq of length %d uses %.2fk\n", '>' x ($_+1), $length, total_size($seq)/1024;
  push @summary, sprintf "%s Faidx object using %.2fk\n", '>' x ($_+1), total_size($index)/1024;
  push @summary, sprintf "%s Perl size using %.2fk\n", '>' x ($_+1), perl_size() / 1024;
  push @summary, sprintf "%s Perl heap using %.2fk\n", '>' x ($_+1), heap_size() / 1024;
}
print "\n\n",join(q{}, @summary),"\n\n";
```

Output now:

```
$ /usr/bin/time -v perl htsFaidx.pl test.fa 3
## some blah from Devel::SizeMe
Faidx object before use is 0.07k
> seq of length 1000000 uses 976.61k
> Faidx object using 0.07k
> Perl size using 2465.36k
> Perl heap using 2465.44k
>> seq of length 1000000 uses 976.61k
>> Faidx object using 0.07k
>> Perl size using 3442.22k
>> Perl heap using 3442.25k
>>> seq of length 1000000 uses 976.61k
>>> Faidx object using 0.07k
>>> Perl size using 4418.92k
>>> Perl heap using 4418.95k
```

**Comment by rishidev** [comment]
Sorry, I was away last week so only saw this yesterday. Thanks for catching this - will start having a look now.

**Comment by andrewyatz** [comment]
I took a bit of a punt and wrapped the allocation of the seq sv with an sv2mortal call. I think it's caused the leak to go away.

**Comment by rishidev** [comment]
That seems to have worked, thanks.

**Comment by andrewyatz** [comment]
Awesome stuff :+1: and it's no longer showing the issue now on my box.

When can we release this to CPAN?

**Comment by rishidev** [comment]
It's just come through ;-)
https://metacpan.org/release/RISHIDEV/Bio-DB-HTS-1.11

**Comment by andrewyatz** [comment]
Awesome work :)
