### ISSUE TITLE
Bio__DB__HTS__VCFfile now defined twice

### ISSUE THREAD

**Issue by jgrigonis** [Ensembl/Bio-DB-HTS#72]
lib/Bio/DB/HTS.xs:80: error: redefinition of typedef ‘Bio__DB__HTS__VCFfile’
lib/Bio/DB/HTS.xs:72: note: previous declaration of ‘Bio__DB__HTS__VCFfile’ was here

Offensive code:

typedef htsFile*        Bio__DB__HTS__VCFfile;
typedef vcfFile*        Bio__DB__HTS__VCFfile;

**Comment by avullo** [comment]
Many thanks Josh, my compiler didn't warn me. This is now fixed to the more appropriate declaration.
