### ISSUE TITLE
Illegal versioning scheme

### ISSUE THREAD

**Issue by mkszuba** [Ensembl/Bio-DB-HTS#75]
The current Bio-DB-HTS versioning scheme is, sadly, incompatible with what Perl expects, and according to a Perl-veteran colleague of mine it is in fact illegal on CPAN, where this module has been present since version 2.10. Specifically, Perl runtime expects version numbers in the form of x.yy to be floating-point numbers - meaning that from the runtime's point of view, 2.10 == 2.1 < 2.9.

Demonstration:
1. Install Bio-DB-HTS version 2.10
2. perl -e 'use Bio::DB::HTS 2.5'

Expected result: in the current versioning scheme 2.10 > 2.5 so it should work.

Actual result: "Bio::DB::HTS version 2.5 required--this is only version 2.10".

At least as far as CPAN is concerned there is no actual violation yet (2.10 < 2.11), however there might be trouble once the module has reached version 2.20 according to the current scheme.

**Comment by tgrego** [comment]
Latest release bumped version to 3.01, let's keep versioning that way now to avoid issues.
Closing
