### ISSUE TITLE
Trouble installing under Ubuntu and Windows

### ISSUE THREAD

**Issue by prishly** [Ensembl/Bio-DB-HTS#77]
Hi,
I'm having trouble installing Bio::DB::HTS under Ubuntu and Windows 10.
Last part of the output is:
"Warning: No success on command[C:\Strawberry\perl\bin\perl.exe Build.PL]
  AVULLO/Bio-DB-HTS-2.11.tar.gz
  C:\Strawberry\perl\bin\perl.exe Build.PL -- NOT OK
Stopping: 'install' failed for 'Bio::DB::HTS'.
Failed during this command:
 AVULLO/Bio-DB-HTS-2.11.tar.gz                : writemakefile NO 'C:\Strawberry\perl\bin\perl.exe Build.PL' returned status 512"
On Ubuntu it's the same message except that the line "C:\Strawberry\perl\bin\perl.exe Build.PL -- NOT OK" is replaced with "/usr/bin/perl Build.PL -- NOT OK"

**Comment by avullo** [comment]
Hi @prishly 

I imagine you're using cpan for the install, can you access the logs to see where it's failing?
Alternatively, you could clone the repo and run the build script directly.

Anyway, from what you report, seems it's failing at the installation step, could it be a permission problem?

**Comment by prishly** [comment]
Hi, thanks for answering.
I tried installing manually through the usual procedure perl Build.PL && ./Build, but that's where it failed becuase Build.PL didn't create any Build exe-file. Could that be the source of error while trying to install through cpan?
Finally I read README, which I guess I should have before, launched INSTALL.pl as recommended in the README doc and the module installed without any errors.

**Comment by avullo** [comment]
Yes, that's the source of error but it doesn't help to diagnose the problem. I will try to reproduce it on a Ubuntu image. Anyway, since you've managed with the INSTALL script, are you happy at the moment?

**Comment by avullo** [comment]
@prishly in order to install via cpan, you need to have Bioperl (the Bio::Root::Version package specifically) and HTSlib installed in common library locations. I was assuming that but can you confirm?
The fact that the install script succeeded is because it installs its own copy of HTSlib.
