### ISSUE TITLE
Reduce Module::Build version dependency

### ISSUE THREAD

**Issue by jmarshall** [Ensembl/Bio-DB-HTS#78]
CentOS 7.5 (released in May) provides Module::Build 0.40.05.

Bio-DB-HTS currently requires Module::Build 0.42, so is difficult to install on the current version of CentOS. You need to either install a bespoke Module::Build or downgrade Bio-DB-HTS's requirements before trying to build it.

M::B 0.42 is functionally identical to 0.40_11, and there doesn't appear to be too much of significance for people installing Bio-DB-HTS in M::B Changes between 0.40 and 0.40_11.

Is there a particular M::B feature that Bio-DB-HTS depends on? It looks a bit like the 0.42 dependency is there simply because relevant files were generated using 0.42xy which produced `configure_requires` entries accordingly (see 115fc165b1d2782c99673894daf3eab88be36878), and is not a strict Bio-DB-HTS requirement.

35cec2c00a40f47cb174315847b4b25226967b59 attempted to reduce the M::B requirement to 0.38, but was reverted in e9cdd6fe66ec7fe952b06ff46936efc3fef85fa5 as “the 0.38 seemed to be ignored on target machines anyway”. It was ignored because the corresponding lines in META.json and META.yml also needed to be changed for this to be effective.

Would you consider reducing the Module::Build version requirement so that Bio-DB-HTS builds out of the box on CentOS 7? I would recommend one of 0.38 (per @rishidev), 0.40, or something in between if there are other common distributions that can be accommodated too. (CentOS 6 provided M::B 0.35.)

This can be done by changing one line in each of Build.PL, META.json, and META.yml — grep for `Module::Build.*42[^0-9]`.

**Comment by avullo** [comment]
Hi @jmarshall 
I'm not aware of any particular dependency on any particular feature of M::B.
I've just downgraded by making the changes to all relevant files.

**Comment by jmarshall** [comment]
Thanks!
