### ISSUE TITLE
BioPerl version

### ISSUE THREAD

**Issue by andrewyatz** [Ensembl/Bio-DB-HTS#8]
Just tried to install from CPAN via cpanm and noticed that it installed BioPerl version 1.69. Is there any particular reason why we need such a late version of BioPerl? Not that I've got any issues surrounding it just could/should it be relaxed?

**Comment by rishidev** [comment]
Hi Andy

I'm not specifying the latest version explicitly - I've listed the pre-requisites and I assume it just gets the latest. I'll have a look see about 
getting it specified at a preferred version in the cpanfile.

Rishi

**Comment by rishidev** [comment]
We can specify a range for a required module. It would be a good idea to set to 1.6 onwards - which would make it compatible with the version used with ensembl web.

**Comment by andrewyatz** [comment]
That sounds sensible :+1:

**Comment by rishidev** [comment]
It now will be happy with BioPerl 1.6.1 onwards (which ensembl web uses). I've got some other things to bundle it in with for a push to CPAN. Thanks for spotting this!
