### ISSUE TITLE
Issues running in ubuntu

### ISSUE THREAD

**Issue by juancresc** [Ensembl/Bio-DB-HTS#80]
I installed using   perl INSTALL.pl because using cpan I always got a problem with htslib. So now when running there's still an issue

machine@1 :~/tephra$ tephra all -c tephra_config.yml
Can't load '/usr/local/lib/x86_64-linux-gnu/perl/5.22.1/auto/Bio/DB/HTS/HTS.so' for module Bio::DB::HTS: libhts.so.2: cannot open shared object file: No such file or directory at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 187.
 at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Bio/DB/HTS/Kseq.pm line 71.
Compilation failed in require at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Bio/DB/HTS/Kseq.pm line 71.
BEGIN failed--compilation aborted at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Bio/DB/HTS/Kseq.pm line 71.
Compilation failed in require at /usr/local/share/perl/5.22.1/Tephra/Stats/Age.pm line 17.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.22.1/Tephra/Stats/Age.pm line 17.
Compilation failed in require at /usr/local/share/perl/5.22.1/Tephra/Command/age.pm line 11.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.22.1/Tephra/Command/age.pm line 11.
Compilation failed in require at /usr/local/share/perl/5.22.1/App/Cmd.pm line 194.
        App::Cmd::_command("Tephra", HASH(0x1336f30)) called at /usr/local/share/perl/5.22.1/App/Cmd.pm line 171
        App::Cmd::new("Tephra", HASH(0x1336f30)) called at /usr/local/bin/tephra line 25

**Comment by avullo** [comment]
@juancrescente can you provide a little bit more context? What's exactly the environment and command you've run?

thanks

**Comment by avullo** [comment]
Closing this as I'm not getting a reply.
