### ISSUE TITLE
INSTALL.pl from cloned repository failing on Ubuntu/perl5.22.1

### ISSUE THREAD

**Issue by pmcarlton** [Ensembl/Bio-DB-HTS#85]
I'm trying to install Bio-DB-HTS as a prerequisite of [BRASS](https://github.com/cancerit/BRASS). I'm using Ubuntu 16.04, perl 5.22.1 (details in Gist at https://gist.github.com/pmcarlton/19dd97bf075160e672938625b700b77d)

I've cloned the git repo and tried to install from within the cloned directory.
`perl INSTALL.pl` is failing with: (see gist for complete log)

```
...
[fai_load] build FASTA index.
panic: sv_setpvn called with negative strlen -1 at t/07cramwrite.t line 117.
panic: sv_setpvn called with negative strlen -1 at t/08bamwrite.t line 117.
Failed 4/11 test programs. 0/397 subtests failed.
Build test failed. Not continuing at INSTALL.pl line 198.
cannot remove path when cwd is /tmp/DaEfuzO1DW/Bio-DB-HTS for /tmp/DaEfuzO1DW:  at /usr/share/perl/5.22/File/Temp.pm line 778.
```

I'm not sure how to go about fixing it, so any advice would be appreciated. Thanks

**Comment by avullo** [comment]
Hi,

it doesn't seem to be a problem of the perl version, I've run with 5.22.1 and it works. I'm having a deeper look.

**Comment by avullo** [comment]
I'm afraid I cannot replicate the issue.
I've set up a vagrant box with Ubuntu 16.04 LTS which comes with perl-5.22.1, installed some HTSlib dependencies (liblzma-dev, libbz2-dev, zlib1-dev) together with BioPerl and Module::Build, cloned the git repo and done an install exactly like you. 
I haven't experienced any problem.

P.S. I've used the kg4giy/ubuntu16puppet box

**Comment by pmcarlton** [comment]
I see; thanks a lot for looking into it. It's probably something about my system perl installation then…will wipe and try again.
