### ISSUE TITLE
Request to honour POSIX ACLs

### ISSUE THREAD

**Issue by CanWood** [Ensembl/Bio-DB-HTS#89]
Hi folks.

Would it be possible to have the access checks on bam files enhanced to check whether or not POSIX ACLs will allow users to access files?  [HTS.pm line 1387](https://github.com/Ensembl/Bio-DB-HTS/blob/master/lib/Bio/DB/HTS.pm#L1387) uses filetest access and, according to the [perldoc for filetest](https://perldoc.perl.org/filetest.html)

> ...you may encounter surprises if your program runs on a system that uses ACLs, since the stat() information won't reflect the actual permissions.

Any chance these tests could be enhanced to allow use of ACL on supporting systems?

Thanks!

**Comment by jmarshall** [comment]
Honouring ACLs is precisely what `use filetest 'access'` does, as added (by you) in PR #49.

Or are you saying there are other places in the code that the pragma could also usefully be used?
If so, where?

**Comment by CanWood** [comment]
Wow.  Long enough ago that I did not remember submitting that!  I'll run some more tests but it's looking to me like my original fix may not have been sufficient. My apologies.  I'll be in touch.

**Comment by sgiorgetti** [comment]
Closing because of aging. Please, re-open this if you feel it's still current
