### ISSUE TITLE
Reduce Module::Build dependency in 2.x branch

### ISSUE THREAD

**Issue by ntm** [Ensembl/Bio-DB-HTS#96]
Hello,
Bio-DB-HTS used to have an excessive dependency on Module::Build v0.42, although 0.38 was sufficent. This broke building on centos7. It was discussed and solved in https://github.com/Ensembl/Bio-DB-HTS/issues/78 by applying this commit: https://github.com/Ensembl/Bio-DB-HTS/commit/801e2ed8fb4a337bcfcf9d552173afdb63058f04

However this was applied to the 3.x branch, while VEP is sticking to the 2.x branch (see https://github.com/Ensembl/ensembl-vep/issues/588 ).
Could the same patch please be applied to 2.x? This should result in VEP INSTALL working on centos7. Thanks!
Regards,
Nicolas

**Comment by sgiorgetti** [comment]
Hello Nicolas,
Thanks for the heads up. We'll look into it and let you know.
Is there any deadline you would like to meet?

Regards,
Stefano

**Comment by ntm** [comment]
Hi Stefano,
there's no pressing need for me, I implemented this fix as a patchfile that I automatically apply to the VEP-downloaded 2.x version of Bio-DB-HTS whenever I update or install VEP on my systems. It works fine, but applying the patch to 2.x on your side would fix the issue for all other VEP users on rhel7 clones.
thanks!
